//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.JsonReader.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.JsonReader.Presentation.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open directory.
        /// </summary>
        public static string Button_OpenDirectory {
            get {
                return ResourceManager.GetString("Button_OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string Header_Exception {
            get {
                return ResourceManager.GetString("Header_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Header_Level {
            get {
                return ResourceManager.GetString("Header_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger.
        /// </summary>
        public static string Header_Logger {
            get {
                return ResourceManager.GetString("Header_Logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Header_Message {
            get {
                return ResourceManager.GetString("Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (+).
        /// </summary>
        public static string Header_PlusSign {
            get {
                return ResourceManager.GetString("Header_PlusSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        public static string Header_ThreadId {
            get {
                return ResourceManager.GetString("Header_ThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Header_Time {
            get {
                return ResourceManager.GetString("Header_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ategories.
        /// </summary>
        public static string Menu_Categories {
            get {
                return ResourceManager.GetString("Menu_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Menu_Category_All {
            get {
                return ResourceManager.GetString("Menu_Category_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Menu_Category_None {
            get {
                return ResourceManager.GetString("Menu_Category_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Columns.
        /// </summary>
        public static string Menu_Columns {
            get {
                return ResourceManager.GetString("Menu_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exception.
        /// </summary>
        public static string Menu_Columns_Exception {
            get {
                return ResourceManager.GetString("Menu_Columns_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Logger.
        /// </summary>
        public static string Menu_Columns_Logger {
            get {
                return ResourceManager.GetString("Menu_Columns_Logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Id.
        /// </summary>
        public static string Menu_Columns_ThreadId {
            get {
                return ResourceManager.GetString("Menu_Columns_ThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time machine.
        /// </summary>
        public static string Menu_Days {
            get {
                return ResourceManager.GetString("Menu_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last files.
        /// </summary>
        public static string Menu_File_History {
            get {
                return ResourceManager.GetString("Menu_File_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Menu_File_Quit {
            get {
                return ResourceManager.GetString("Menu_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Filters.
        /// </summary>
        public static string Menu_Filters {
            get {
                return ResourceManager.GetString("Menu_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _Level.
        /// </summary>
        public static string Menu_Filters_OnLevel {
            get {
                return ResourceManager.GetString("Menu_Filters_OnLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show last.
        /// </summary>
        public static string Menu_Filters_OnTime {
            get {
                return ResourceManager.GetString("Menu_Filters_OnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Menu_Order {
            get {
                return ResourceManager.GetString("Menu_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Menu_Order_Asc {
            get {
                return ResourceManager.GetString("Menu_Order_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Menu_Order_Desc {
            get {
                return ResourceManager.GetString("Menu_Order_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Menu_Source {
            get {
                return ResourceManager.GetString("Menu_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv file.
        /// </summary>
        public static string Menu_Source_Csv {
            get {
                return ResourceManager.GetString("Menu_Source_Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle database.
        /// </summary>
        public static string Menu_Source_OracleDb {
            get {
                return ResourceManager.GetString("Menu_Source_OracleDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} hours.
        /// </summary>
        public static string MenuItem_FilterHours {
            get {
                return ResourceManager.GetString("MenuItem_FilterHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} minute.
        /// </summary>
        public static string MenuItem_FilterLastMinute {
            get {
                return ResourceManager.GetString("MenuItem_FilterLastMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} minutes.
        /// </summary>
        public static string MenuItem_FilterMinutes {
            get {
                return ResourceManager.GetString("MenuItem_FilterMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string MenuItem_NoFilter {
            get {
                return ResourceManager.GetString("MenuItem_NoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you want to load do not exist..
        /// </summary>
        public static string Message_FileNotExist {
            get {
                return ResourceManager.GetString("Message_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File changed..
        /// </summary>
        public static string Status_FileChanged {
            get {
                return ResourceManager.GetString("Status_FileChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loaded..
        /// </summary>
        public static string Status_FileLoaded {
            get {
                return ResourceManager.GetString("Status_FileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V {0}.
        /// </summary>
        public static string Status_Version {
            get {
                return ResourceManager.GetString("Status_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item(s)..
        /// </summary>
        public static string Status_xxItems {
            get {
                return ResourceManager.GetString("Status_xxItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string.
        /// </summary>
        public static string Title_DbConnectionString {
            get {
                return ResourceManager.GetString("Title_DbConnectionString", resourceCulture);
            }
        }
    }
}
